name: main pipeline

on: [pull_request]

defaults:
  run:
    working-directory: ./codebase/rdicidr-0.1.0

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '15.x'
      - name: install dependencies
        run: npm ci
      - name: linting
        run: npm run lint
  
  formatter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '15.x'
      - name: install dependencies
        run: npm ci
      - name: install prettier
        run: npm install -g prettier
      - name: formating
        run: npm run prettier
  
  tester:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '15.x'
      - name: install dependencies
        run: npm ci
      - name: testing
        run: CI=true npm run test 

  builder:
    runs-on: ubuntu-latest
    needs: ['linter', 'formatter', 'tester']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '15.x'
      - name: install dependencies
        run: npm ci
      - name: building
        run: npm run build
